spring:
  profiles:
    active: local
  batch:
    job:
      # JOB? ??? ???? ??? ?? ????? ?? JOB?? ????.
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    # wsl2 ? ????? ????? ifconfig ? wsl2? ???? ??? ??????.
    url: jdbc:mysql://172.29.155.171:3306/house
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: house
    password: house
  jpa:
    show-sql: true
    # Spring? EntityScan? ?? @Entity ?????? ??? ???? ?? generate-ddl ???
    # true? ??? ?? ???? ??? ?? ?? ??? DDL?? ???? DB? ????.(??? ??)
    generate-ddl: false
    hibernate:
      # ddl? ??? none = ???? ???? ???(???? DB?? ???)
      ddl-auto: none
    defer-datasource-initialization: false
  batch:
    jdbc:
      # ??? schema? ?? ??? ??.
      initialize-schema: ALWAYS
