spring:
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_commets: true
  datasource:
    driver-class-name: org.H2.Driver
    username: userName
    password: 1234

logging.level:
  org.hibernate.SQL: debug

#debug: true