spring:
  config:
    import:
      vault:
  #  main:
#    web-application-type: none
  datasource:
    username:
    password:
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_commets: true
  application:
    name: spring-boot-study
  cloud:
    vault:
      scheme: http
      authentication: token
      token: hvs.l8djjt6g2OzsXaCMmox49W6i
  profiles:
    active: test

#  cache:
#    type: redis

# h2 데이터베이스도 config 파일없이 이곳에서 설정할 수 있다.
#  datasource:
#    driver-class-name: org.H2.Driver
#    username: userName
#    password: 1234

logging.level:
  org.hibernate.SQL: debug

#debug: true

# 프로퍼티 설정
api:
  custom:
    properties:
      age: 30
      
